### ISSUE TITLE
In place write strips out comments

### ISSUE THREAD

**Issue by jmreicha** [mikefarah/yq#19]
The CLI strips out comments given the following yaml file:

```
# comment
a:
  b:
```

Using the following command for my test:

`yaml w -i test.yml a.b.c[0] "test"`

**Comment by jmreicha** [comment]
Apparently it also strips out both single `'` and double `"` quotes from arrays.

```
a:
  b:
    c:
    - 'test'
    - "test2"
```

Command I used:

`yaml w test.yml a.b.c[1] "test2"`

Let me know if you want a separate issue for this behavior.

**Comment by mikefarah** [comment]
yep this is because it parses the yaml file using https://godoc.org/gopkg.in/yaml.v2, and then spits it out again.

This means it will not parse comments nor will it differentiate between those quotes if it is required to (for instance if the value is double quotes surrounded by singles ('"')  ).

**Comment by jmreicha** [comment]
Got it, thanks.

**Comment by nemchik** [comment]
@mikefarah is there a way to get yq to NOT strip quotes? I'm using yq for Docker Compose and I need to keep quotes around ports like this
```
ports:
 - "3000"
 - "3000-3005"
 - "8000:8000"
 - "9090-9091:8080-8081"
 - "49100:22"
 - "127.0.0.1:8001:8001"
 - "127.0.0.1:5000-5010:5000-5010"
 - "6060:6060/udp"
```

**Comment by mikefarah** [comment]
Not at the moment - and given how it works with the yaml.v2 I'm not sure it can sorry :(

There may be a workaround I'm not aware of, I'll reopen this issue.

**Comment by nemchik** [comment]
Ok. Thanks for reopening the issue. Here is the source I'm referencing https://docs.docker.com/compose/compose-file/

```
Note: When mapping ports in the HOST:CONTAINER format, you may experience erroneous results when using a container port lower than 60, because YAML parses numbers in the format xx:yy as a base-60 value. For this reason, we recommend always explicitly specifying your port mappings as strings.
```

**Comment by IdanAdar** [comment]
Is there any way to re-add the quotes via some command, though?

**Comment by jeking3** [comment]
Too bad it does this, I have to abandon using it because it removes comments.

**Comment by devdream02** [comment]
@IdanAdar Have you found the solution of re-adding the quotes?
@mikefarah Any update when this functionality be added ?
Thanks!

**Comment by IdanAdar** [comment]
I have not.

**Comment by devdream02** [comment]
> I have not.

Can you suggest any work around or some other library?

**Comment by IdanAdar** [comment]
No. In my case it just happened to continue working even without the quotes.

**Comment by evanstucker-hates-2fa** [comment]
This might be useful...

https://kev.inburke.com/kevin/more-comment-preserving-configuration-parsers/

I don't know Go, but someone wrote a library for it here:

https://gist.github.com/kevinburke/07a21855df700b0acdea9e91c6fde7cf

**Comment by danielfbm** [comment]
+1 for preserving comments. yq is a great tool, and we currently use it to automatically update our helm charts when a docker image changes

As in most helm chart's values.yaml file, the optional values that have a complex format/complex objects are generally commented, therefore it is really required to keep the comments in order to inform the user on how to customize these values.

I can think of a few workarounds to this using different files in our pipeline etc., but would be really appreciated if yq just preserved the comments

**Comment by shaleh** [comment]
https://ubuntu.com/blog/api-v3-of-the-yaml-package-for-go-is-available

It looks like moving to the v3 parser is the solution.

**Comment by andye2004** [comment]
@shaleh reading the release details you linked to I can see that it will solve the comments issue, but I can't see anything about quoted values. Am I missing something?

**Comment by mikefarah** [comment]
Yup - I've looked into the new library, looks really neat - but it requires significant rework of yq which I just don't have time for atm

**Comment by mikefarah** [comment]
@andye2004 when I played with it you could preserve quotes

**Comment by danielfbm** [comment]
any update on this issue? I am willing to collaborate if you will have me

**Comment by alexlemaire** [comment]
Following up on that: would really love to have comments preserved when updating files in place :+1: 

I am using `yq` to update config files where I'd like to leave comments to give some extra hints to the users of this config file via comments.

**Comment by mikefarah** [comment]
Just released a new version of yaml that fixes this - it's a pretty significant update so it's still in beta: https://github.com/mikefarah/yq/releases/tag/3.0.0-beta

**Comment by jhagege** [comment]
> Just released a new version of yaml that fixes this - it's a pretty significant update so it's still in beta: https://github.com/mikefarah/yq/releases/tag/3.0.0-beta

Hi, looks great. 
Is it possible to update a value with double quotes ?

**Comment by mikefarah** [comment]
Yep - if you're wrapping with double quotes (so you can interpolate ENVLIST) then you'll need to escape the inner quotes.

```
x=thing
yq n services "\"cat${x}\""
```

will yield
```
services: '"catthing"'
```

That this therefore has the value "catthing" when reading the yaml.

If you want a single pair of quotes:
```
services: "catthing"
```

Then at the moment v3 does not support this, instead it only quotes values when required. It could support an override by passing in a 'style' flag (https://godoc.org/gopkg.in/yaml.v3#Style).

**Comment by mikefarah** [comment]
Sidenote:
```
services: catthing
```
and 
```
services: "catthing"
```

Both effectively have the same values...

**Comment by jhagege** [comment]
Great, thanks for the quick and clear response.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1

**Comment by mat926** [comment]
I'm still having this issue even on 4.44.2 . I have a command like
 yq '.rffmpeg.directories.owner = "dockerlimited"' /config/rffmpeg.yml -i

But the quotes around dockerlimited do not get preserved.
