### ISSUE TITLE
Alpine apk instructions incorrect

### ISSUE THREAD

**Issue by kssun-msts** [mikefarah/yq#552]
**Describe the bug**
The alpine apk add instruction seems to be incorrect as the package is in the edge/community path and not simply "community"

version of yq: 3.4.0
operating system: N/A

**Input md**

README.md:
### Alpine Linux
- Enable community repo by adding ```$MIRROR/alpine/v$VERSION/community``` to ```/etc/apk/repositories```
- Update database index with ```apk update```
- Install yq with ```apk add yq```

Should be:
- Enable edge/community repo by adding ```$MIRROR/alpine/edge/community``` to ```/etc/apk/repositories```

**Command**
The command you ran:
N/A, as community packages path was already present in Alpine 3.12

**Actual behavior**

```
apk add yq
ERROR: unsatisfiable constraints:
  yq (missing):
    required by: world[yq]
```

**Expected behavior**

```
apk add --update yq
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/1) Installing yq (3.4.0-r0)
Executing busybox-1.31.1-r16.trigger
OK: 147 MiB in 67 packages
```

**Additional context**
Your packages don't seem to be in the standard Alpine community repo paths, they seem to be in the "edge" path.
Is here: http://dl-cdn.alpinelinux.org/alpine/edge/community/
Not here: http://dl-cdn.alpinelinux.org/alpine/v3.12/main/

Alpine image for 3.12 already had a community repo path in the list.

**Comment by mikefarah** [comment]
Fixed - thanks :)

**Comment by MohamedLEGH** [comment]
Gitbook is still showing the wrong link : https://mikefarah.gitbook.io/yq/#alpine-linux

**Comment by mikefarah** [comment]
oops - thanks @MohamedLEGH
