### ISSUE TITLE
referencing nested arrays incompatible with yq 4.0.0

### ISSUE THREAD

**Issue by akloss-cibo** [mikefarah/yq#824]
**Describe the bug**

yq 4.9.0 (and perhaps earlier versions) can't handle array expressions that worked in older versions of yq.

Version of yq: 4.9.0
Operating system: mac (Darwin Kernel Version 19.6.0) / linux (ubuntu 20.04 docker image)
Installed via: Binary release and Homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
- - zero
```

**Command**
The command you ran:
```
% echo '- - zero' | ./yq-4.0.0 eval '.[0].[0]' -
zero
% yq -V
yq version 4.9.1
% echo '- - zero' | yq eval '.[0].[0]' -
Error: Bad expression, please check expression syntax
%
```

This is also pretty unexpected, at least to me:
```
% echo '- - zero' | yq eval '.[0][0]' -
- zero
%
```
Note that the output is not `zero`, it's `- zero`, the second `[0]` is silently ignored.

**Comment by mikefarah** [comment]
That is strange - I'll look into that.

In the mean time - as a workaround, you can:

```
 echo '- - zero' | ./yq eval '.[0] | .[0]' -
```

**Comment by akloss-cibo** [comment]
👍 

FWIW, I've been using
```
echo '- - zero' | yq eval '(.[0])[0]' -
```

**Comment by mikefarah** [comment]
Fixed in 4.9..2 :)

**Comment by mikefarah** [comment]
oh and its `.[0][0]`

**Comment by akloss-cibo** [comment]
Thanks for looking at this!  Unfortunately, it didn't fix my original problem that scripts that worked in older yq doesn't work in newer ones:
```
% echo '- - zero' | ./yq-4.0.0 eval '.[0].[0]' -
zero
% yq -V
yq version 4.9.3
% echo '- - zero' | yq eval '.[0].[0]' -
Error: Bad expression, please check expression syntax
%
```

While supporting `.[0].[0]` may not have been intended, older yq implemented it _and_ does not implement `.[0][0]`, so we'll have to update our scripts prior to upgrading...
```
% echo '- - zero' | ./yq-4.0.0 eval '.[0][0]' -
Error: expected end of expression but found '0', please check expression syntax
%
```
which is managable... we'd already started pinning yq to a specific version so we're in a good position to do that.
